tasks:
  - init: go env -w GO111MODULE=off &&
          go get github.com/devlights/mkghurl &&
          go env -u GO111MODULE
    command: if [ -n "$GITHUB_TOKEN" ]; then git remote set-url origin $(mkghurl try-shellscript); fi && bash --version | head -n 1
image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - timonwong.shellcheck@0.9.0:hsU/Rd39aqPYowTqL+DbXg==
    - mads-hartmann.bash-ide-vscode@1.4.0:/qx+rdXE/fGTGWhelNf3aQ==
